env_id: CarRacing
reward:
  use_native: false
  progress_scale: 1.0
  step_penalty: 0.1
  offtrack_penalty: 1.0
  finish_bonus: 100.0
termination:
  offtrack_frames: 50
  no_progress_steps: 100
agent:
  needs_pixels: true
  resize: 84
  frame_stack: 4
  discrete_wrapper: true
  action_set: dqn5_simple
